export const dataTypes = [
  "Boolean",
  "Coded",
  "Complex",
  "Date",
  "Datetime",
  "Document",
  "None",
  "Numeric",
  "Rule",
  "Structured-Numeric",
  "Text",
  "Time",
];

export const conceptClasses = [
  "Test",
  "Procedure",
  "Drug",
  "Diagnosis",
  "Finding",
  "Anatomy",
  "Question",
  "LabSet",
  "MedSet",
  "ConvSet",
  "Misc",
  "Symptom",
  "Symptom/Finding",
  "Specimen",
  "Misc Order",
  "Program",
  "State",
  "Medical supply",
  "Code",
  "Radiology/Imaging Procedure",
  "Concept Class",
  "Indicator",
  "Drug form",
  "Units of Measure",
  "Frequency",
  "Pharmacologic Drug Class",
  "Workflow",
  "Organism",
  "none",
  "Products",
  "InteractSet",
];
